WebUI/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PlaneStore.Application.Models;

namespace PlaneStore.WebUI.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

WebUI/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using PlaneStore.Application.Models;
using PlaneStore.Application.Services;
using PlaneStore.WebUI.Models;

namespace PlaneStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private readonly IAircraftService _aircraftService;
        private readonly Cart _cart;

        public CartController(IAircraftService aircraftService, Cart cart)
        {
            _aircraftService = aircraftService;
            _cart = cart;
        }

        public ViewResult Index(string returnUrl = "/")
        {
            return View(new CartViewModel
            {
                Cart = _cart,
                ReturnUrl = returnUrl,
            });
        }

        [HttpPost]
        public IActionResult Add(Guid aircraftId, string returnUrl)
        {
            var aircraft = _aircraftService.GetAircraftById(aircraftId);
            if (aircraft is not null)
            {
                _cart.AddItem(aircraft, 1);
            }

            return RedirectToAction(nameof(Index), new { returnUrl });
        }

        [HttpPost]
        public IActionResult Remove(Guid aircraftId, string returnUrl)
        {
            var aircraft = _aircraftService.GetAircraftById(aircraftId);
            if (aircraft is not null)
            {
                _cart.RemoveItem(aircraft);
            }

            return RedirectToAction(nameof(Index), new { returnUrl });
        }
    }
}

WebUI/Views/Shared/AircraftSummary.cshtml
@model Aircraft

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-light p-1">
        <h4>
            @Model.Name
            <span class="badge rounded-pill bg-primary text-white" style="float: right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
        <h6>@Model.Manufacturer.Name</h6>
    </div>
    <form asp-controller="Cart" asp-action="Add" method="post">
        <input type="hidden" name="aircraftId" value="@Model.Id" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success btn-sm pull-right" style="float: right">Add To Cart</button>
        </span>
    </form>
</div>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Planes Store</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <nav class="navbar bg-dark text-white p-2">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="#">PLANES STORE</a>
            <div class="d-flex navbar-text text-end">
                @await Component.InvokeAsync("CartSummary")
            </div>
        </div>
    </nav>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout_old.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlaneStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PlaneStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PlaneStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>